version: '2'

services:
  app:
    image: 'challenge-api:latest'
    build:
      context: .
    container_name: challenge-api
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://challenge-db:5432/tenpo_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=pstgrspwd
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: challenge-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pstgrspwd
      - POSTGRES_DB=tenpo_db
